blood_bank/blood_bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('donor/', include('donors.urls')),
    path('hospital/', include('hospitals.urls'))
]

blood_bank/donors/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('register/', views.register_donor, name='register_donor'),
    path('donate/', views.donate, name='donate'),
]

blood_bank/hospitals/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('register/', views.register_hospital, name='register_hospital'),
    path('request/', views.request, name='request'), 
    path('request_list/', views.request_list, name='request_list'),
]

blood_bank/hospitals/models.py
from django.db import models

from accounts.models import CustomUser
from stock.models import BloodUnit

class Hospital(models.Model):
    user = models.OneToOneField(
        CustomUser, on_delete=models.CASCADE, related_name='hospital'
    )
    hospital_name = models.CharField(max_length=150, null=False, blank=False)
    
    class Meta:
        verbose_name = 'Hospital'
        verbose_name_plural = 'Hospitals'

class HospitalRequest(models.Model):
    class PatientStatus(models.IntegerChoices):
        IMMEDIATE = 1, 'Immediate'
        URGENT = 2, 'Urgent'
        NORMAL = 3, 'Normal'
    class RequestStatus(models.IntegerChoices):
        ACCEPTED = 1, 'Accepted'
        REJECTED = 2, 'Rejected'
        PENDING = 3, 'Pending'

    hospital = models.ForeignKey(
        Hospital,
        on_delete=models.CASCADE,
        related_name='requests_created',
    )
    request_date = models.DateTimeField(auto_now_add=True)
    number_of_units = models.PositiveIntegerField(blank=False, null=False)
    blood_type = models.PositiveSmallIntegerField(choices=BloodUnit.BloodType.choices, blank=False, null=False)
    patient_status = models.PositiveSmallIntegerField(choices=PatientStatus.choices, blank=False, null=False)
    request_status = models.PositiveSmallIntegerField(choices=RequestStatus.choices, blank=False, null=False)
    
    class Meta:
        ordering = ['-request_date']

blood_bank/hospitals/forms.py
from django import forms

from .models import Hospital, HospitalRequest

class HospitalRegisterationForm(forms.ModelForm):
    class Meta:
        model = Hospital
        fields = ['hospital_name']

class HospitalRequestForm(forms.ModelForm):
    class Meta:
        model = HospitalRequest
        fields = ['number_of_units', 'blood_type', 'patient_status']

blood_bank/hospitals/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from accounts.models import CustomUser
from accounts.forms import UserRegistrationForm

from .forms import HospitalRegisterationForm, HospitalRequestForm
from .models import HospitalRequest, Hospital
from .tasks import process_requests

def register_hospital(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        user_specific_form = HospitalRegisterationForm(request.POST)

        if user_form.is_valid() and user_specific_form.is_valid:
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.role = CustomUser.Role.HOSPITAL
            new_user.save()
            new_donor = user_specific_form.save(commit=False)
            new_donor.user = new_user
            new_donor.save()
            messages.success(request, 'You have successfully created your account, you can login to it.')
            return redirect('dashboard')
    else:
        user_form = UserRegistrationForm()
        user_specific_form = HospitalRegisterationForm()

    return render(
        request,
        'account/register.html',
        {
            'user_form': user_form,
            'user_specific_form': user_specific_form
        }
    )

@login_required
def request(request):
    if request.user.role == CustomUser.Role.HOSPITAL:
        if request.method == 'POST':
            request_form = HospitalRequestForm(request.POST)
            if request_form.is_valid():
                new_request = request_form.save(commit=False)
                hospital = Hospital.objects.get(user=request.user)
                new_request.hospital = hospital
                new_request.request_status = HospitalRequest.RequestStatus.PENDING
                new_request.save()
                # print(r.get(f'blood_type:{BloodType.A_POS}'))
                process_requests.delay()
                messages.success(
                    request,
                    'Your request has been submitted successfully, You can check the updates through your requests list.'
                )
                return redirect('dashboard')
            else:
                messages.error(request, 'Error submitting your form.')
        else:
            request_form = HospitalRequestForm()
    else:
        messages.error(request, 'You are not authorized to go to this page.')
        return redirect('dashboard')
        
    return render(
        request,
        'request/request.html',
        {'request_form': request_form}
    )

@login_required
def request_list(request):
    if request.user.role == CustomUser.Role.HOSPITAL:
        requests = request.user.hospital.requests_created.all()
        paginator = Paginator(requests, 5)
        page = request.GET.get('page')

        try:
            requests = paginator.page(page)
        except PageNotAnInteger:
            requests = paginator.page(1)
        except EmptyPage:
            requests = paginator.page(paginator.num_pages)
        return render(
            request,
            'request/request_list.html',
            {'requests': requests}
        )
    
    else:
        messages.error(request, 'You are not authorized to go to this page.')
        return redirect('dashboard')

blood_bank/hospitals/templates/request/request.html
{% extends "base.html" %}

{% block title %}Donate{% endblock %}

{% block content %}
    <h1>Request</h1>
    <p>Please, fill the following form:</p>
    <form method="post" novalidate>
        {{ request_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Request"></p>
    </form>
{% endblock %}

blood_bank/hospitals/templates/request/request_list.html
{% extends "base.html" %}

{% block title %}Requests{% endblock %}

{% block content %}
    <h1>Requests</h1>
    <div class="table-container">
        <table class="requests-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Date</th>
                    <th>Units</th>
                    <th>Blood Type</th>
                    <th>Patient Status</th>
                    <th>Request Status</th>
                </tr>
            </thead>
            <tbody>
                {% for request in requests %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ request.request_date }}</td>
                            <td>{{ request.number_of_units }}</td>
                            <td>{{ request.get_blood_type_display }}</td>
                            <td>{{ request.get_patient_status_display }}</td>
                            <td>{{ request.get_request_status_display }}</td>
                        </tr>
                {% endfor %}
            </tbody>    
        </table>
    </div>
    {% include "pagination.html" with page=requests %}
{% endblock %}
    

blood_bank/hospitals/templates/request/request_update_email.html
You have recieved new updates about your early request.\n\n
Please, go to your portal so you can see what is going on.